name: web-redirect
title: Web Redirector
base: core22
version: 1.0.0
summary: Simple snap to add entry into the sidebar
description: |
  This is a sample snap that will an entry in the sidebar

grade: stable
confinement: strict

parts:
  dump:
    plugin: dump
    source: ./dump

apps:
  my-service:
    command: bin/service.sh
    daemon: simple
    plugs:
      - active-solution

plugs:
  active-solution: 
    interface: content
    content: solutions
    target: $SNAP_DATA/solutions

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP_DATA/package-assets/$SNAPCRAFT_PROJECT_NAME
      

hooks:
  connect-plug-active-solution:
    plugs: [active-solution]   
  post-refresh:    
    plugs: [active-solution]   