#!/bin/bash
mkdir -p $SNAP_DATA/solutions/activeConfiguration/web-redirect/package-assets
cp -rf $SNAP/package-assets/package-manifest.json $SNAP_DATA/solutions/activeConfiguration/web-redirect/package-assets/package-manifest.json


#mkdir -p $SNAP_DATA/solutions/activeConfiguration/web-redirect
#mkdir -p $SNAP_DATA/solutions/activeConfiguration/web-redirect/package-assets
#cp $SNAP/DumpedData/testfile.txt $SNAP_DATA/solutions/activeConfiguration/web-redirect/package-assets
#cp $SNAP/package-assets/package-manifest.json $SNAP_DATA/solutions/activeConfiguration/web-redirect/package-assets
